import type { IMAlbum } from "../types";

export default {
  title: "珍珠之歌2",
  titleEn: "The Shimmering Voyage Vol. 2",
  image: "https://p2.music.126.net/Ng-Y1hnNpxkMX8goopSrWA==/109951167795916089.jpg",
  musics: [
    {
      subtitle: "远海诗夏游纪·鸣弦列岛",
      tracks: [
        {
          title: "熙焰明光",
          titleEn: "Flickering Brightness",
          scene: "探索",
          start: 0,
          links: {
            ne: 1973619547,
            qq: "0023IjfU4SwvSB",
          },
          credits: [
            ["作曲", "陈致逸 (HOYO-MiX)", "姜以君 (HOYO-MiX)"],
            ["编曲", "陈致逸 (HOYO-MiX)", "姜以君 (HOYO-MiX)"],
            ["指挥", "Robert Ziegler"],
            ["乐队", "伦敦爱乐乐团"],
            ["竹笛", "丁晓逵"],
            ["古筝", "申依靖"],
            ["二胡", "王颖"],
            ["录音棚", "Air Studios", "Ready Steady Sound!"],
            ["录音师", "Nick Wollage", "Laurence Anslow", "陈冠男"],
            ["混音师", "Nick Wollage", "姜以君 (HOYO-MiX)"],
            ["母带制作", "黄巍"],
            ["出品", "HOYO-MiX"],
          ],
        },
        {
          title: "烈火轰雷",
          titleEn: "Burst Into Flames",
          scene: "战斗",
          start: 0,
          links: {
            ne: 1973619548,
            qq: "003hxWZA32u0ux",
          },
          credits: [
            ["作曲", "陈致逸 (HOYO-MiX)", "姜以君 (HOYO-MiX)"],
            ["编曲", "陈致逸 (HOYO-MiX)", "姜以君 (HOYO-MiX)"],
            ["指挥", "Robert Ziegler"],
            ["乐队", "伦敦爱乐乐团"],
            ["竹笛", "丁晓逵"],
            ["古筝", "申依靖"],
            ["二胡", "王颖"],
            ["电吉他", "姜以君 (HOYO-MiX)"],
            ["录音棚", "Air Studios", "Ready Steady Sound!"],
            ["录音师", "Nick Wollage", "Laurence Anslow", "陈冠男"],
            ["混音师", "Nick Wollage", "姜以君 (HOYO-MiX)"],
            ["母带制作", "黄巍"],
            ["出品", "HOYO-MiX"],
          ],
        },
      ],
    },
    {
      subtitle: "诀箓阴阳寮",
      tracks: [
        {
          title: "「诀箓阴阳寮」未发布曲目1",
          titleEn: "Unnamed Mystic Onmyou Chamber Soundtrack 1",
          scene: "探索",
          start: 3.6,
          links: {
            fandom: "Mystic_Onmyou_Chamber_Against_the_Invisible_Net_Var.ogg",
          },
        },
        {
          title: "难逃之阵",
          titleEn: "Against the Invisible Net",
          scene: "战斗",
          start: 0,
          links: {
            ne: 1879108767,
            qq: "003tqCAq24fCdZ",
          },
          credits: [
            ["作曲", "陈致逸 (HOYO-MiX)"],
            ["指挥", "栗田 博文"],
            ["乐队", "東京フィルハーモニー交響楽団"],
            ["乐队配器", "陈致逸 (HOYO-MiX)"],
            ["尺八", "寄田 真見乃"],
            ["筝", "渡邊 香澄"],
            ["太鼓", "太鼓芸能集団 鼓童"],
            ["附加弦乐", "国际首席爱乐乐团"],
            ["短笛", "刘纯"],
            ["长笛", "程晓华", "刘颖熙"],
            ["双簧管", "袁小钢", "丛众一"],
            ["降E调单簧管", "刘峤"],
            ["降B调单簧管", "庾慧晶"],
            ["A调单簧管", "吴丹"],
            ["低音单簧管", "李翰琪"],
            ["大管", "王昱平", "谢圣娴"],
            ["低音大管", "柯燕芳"],
            ["录音棚", "Heartbeat Recording Studio", "SoundCity", "Tokyo Opera City Concert Hall", "金田录音棚"],
            ["舞台监督", "稲岡 宏司"],
            ["乐团经理", "岩崎 井織"],
            ["录音现场指导", "宮野 幸子 (SHANGRI-LA Inc.)"],
            ["音乐监制", "千葉 智史 (Sony Music Publishing (Japan) Inc.)", "宮野 幸子 Sachiko Miyano (SHANGRI-LA Inc.)"],
            ["录音师", "立石 佑太 (SHANGRI-LA Inc.)", "齋藤 春樹 (SoundCity)", "鈴木 浩二 (Sony Music Studio)", "村松 健 (Octavia Records Inc.)", "王小四", "肖广一"],
            ["混音师", "Simon Rhodes"],
            ["母带制作", "Simon Gibson"],
            ["联合制作", "Sony Music Entertainment (Japan) Inc."],
            ["出品", "HOYO-MiX"],
          ],
        },
      ],
    },
    {
      subtitle: "诀箓阴阳寮",
      tracks: [
        {
          title: "「诀箓阴阳寮」未发布曲目2",
          titleEn: "Unnamed Mystic Onmyou Chamber Soundtrack 2",
          scene: "探索",
          start: 3.3,
          links: {
            fandom: "Mystic_Onmyou_Chamber_Duel_in_the_Mist_Var.ogg",
          },
        },
        {
          title: "斩雾破竹",
          titleEn: "Duel in the Mist",
          scene: "战斗",
          start: 0,
          links: {
            ne: 1879108765,
            qq: "000Kz20B3PpCfO",
          },
          credits: [
            ["作曲", "陈致逸 (HOYO-MiX)"],
            ["乐队配器", "陈致逸 (HOYO-MiX)"],
            ["尺八", "寄田 真見乃"],
            ["津轻三味线", "小山 豊", "駒田 早代"],
            ["筝", "渡邊 香澄"],
            ["太鼓", "太鼓芸能集団 鼓童"],
            ["录音棚", "Shangri-la Studio", "SoundCity"],
            ["音乐监制", "千葉 智史 (Sony Music Publishing (Japan) Inc.)"],
            ["录音师", "立石 佑太 (SHANGRI-LA Inc.)", "齋藤 春樹 (SoundCity)", "鈴木 浩二 (Sony Music Studio)"],
            ["混音师", "Simon Rhodes"],
            ["母带制作", "Simon Gibson"],
            ["联合制作", "Sony Music Entertainment (Japan) Inc."],
            ["出品", "HOYO-MiX"],
          ],
        },
      ],
    },
    {
      subtitle: "诀箓阴阳寮",
      tracks: [
        {
          title: "「诀箓阴阳寮」未发布曲目3",
          titleEn: "Unnamed Mystic Onmyou Chamber Soundtrack 3",
          scene: "探索",
          start: 1.75,
          links: {
            fandom: "Mystic_Onmyou_Chamber_Overlord_of_the_Thunderstorm_Var.ogg",
          },
        },
        {
          title: "空行不羁",
          titleEn: "Overlord of the Thunderstorm",
          scene: "战斗",
          start: 0,
          links: {
            ne: 1879108774,
            qq: "003HZNWA36390K",
          },
          credits: [
            ["作曲", "陈致逸 (HOYO-MiX)"],
            ["指挥", "栗田 博文"],
            ["乐队", "東京フィルハーモニー交響楽団"],
            ["乐队配器", "陈致逸 (HOYO-MiX)"],
            ["尺八", "寄田 真見乃"],
            ["津轻三味线", "小山 豊", "しゃみお"],
            ["筝", "渡邊 香澄"],
            ["太鼓", "太鼓芸能集団 鼓童"],
            ["附加弦乐", "国际首席爱乐乐团"],
            ["录音棚", "Shangri-la Studio", "音響ハウス", "SoundCity", "Tokyo Opera City Concert Hall", "金田录音棚"],
            ["舞台监督", "稲岡 宏司"],
            ["乐团经理", "岩崎 井織"],
            ["录音现场指导", "宮野 幸子 (SHANGRI-LA Inc.)"],
            ["音乐监制", "千葉 智史 (Sony Music Publishing (Japan) Inc.)", "山村 涼 (Sony Music Publishing (Japan) Inc.)", "宮野 幸子 Sachiko Miyano (SHANGRI-LA Inc.)"],
            ["录音师", "立石 佑太 (SHANGRI-LA Inc.)", "吉羽 貴史 (Smart Break Sound)", "齋藤 春樹 (SoundCity)", "鈴木 浩二 (Sony Music Studio)", "村松 健 (Octavia Records Inc.)", "王小四"],
            ["混音师", "Simon Rhodes"],
            ["母带制作", "Simon Gibson"],
            ["联合制作", "Sony Music Entertainment (Japan) Inc."],
            ["出品", "HOYO-MiX"],
          ],
        },
      ],
    },
  ],
} as IMAlbum;
