import type { IMAlbum } from "../types";

export default {
  title: "智妙明论之林",
  titleEn: "Forest of Jnana and Vidya",
  image: "https://p1.music.126.net/mi40R92CSJ6zeroCvLxQQA==/109951167997564898.jpg",
  musics: [
    {
      subtitle: "桓那兰那",
      tracks: [
        {
          title: "沃土新芽的曲调",
          titleEn: "Melody of Bright New Buds",
          scene: "一般区域",
          start: 0,
          links: {
            ne: 1992343571,
            qq: "000z51y92o6G0X",
          },
          credits: [
            ["作曲", "陈致逸 (HOYO-MiX)"],
            ["编曲", "陈致逸 (HOYO-MiX)"],
            ["班苏里笛", "Eliza Marshall"],
            ["西塔尔琴", "Jonathan Mayer"],
            ["民乐监制", "Kuljit Bhamra"],
            ["录音棚", "Redfort Studio"],
            ["录音师", "Kuljit Bhamra"],
            ["音频编辑", "George Oulton", "Freddie Light"],
            ["混音师", "Lewis Jones"],
            ["母带制作", "Simon Gibson"],
            ["出品", "HOYO-MiX"],
          ],
        },
        {
          title: "和合大梦的曲调",
          titleEn: "Melody of Brave Seeds",
          scene: "幻梦之门",
          start: 0.16,
          links: {
            ne: 1992344596,
            qq: "002o7XY83eQBtm",
          },
          credits: [
            ["作曲", "陈致逸 (HOYO-MiX)"],
            ["编曲", "陈致逸 (HOYO-MiX)"],
            ["西塔尔琴", "Jonathan Mayer"],
            ["合唱指挥", "齐放"],
            ["合唱", "Sfuture艺术团"],
            ["民乐监制", "Kuljit Bhamra"],
            ["录音棚", "Redfort Studio", "Sound Pro Studio"],
            ["录音师", "Kuljit Bhamra", "曹晓冬"],
            ["音频编辑", "George Oulton", "Freddie Light", "徐威"],
            ["混音师", "Lewis Jones", "黄巍"],
            ["母带制作", "Simon Gibson"],
            ["出品", "HOYO-MiX"],
          ],
        },
      ],
    },
    {
      subtitle: "桓那兰那",
      tracks: [
        {
          title: "颠倒梦想的曲调",
          titleEn: "Melody of Sprouting Flowers",
          scene: "一般区域",
          start: 0,
          links: {
            ne: 1992344593,
            qq: "002FJr6O26PIOH",
          },
          credits: [
            ["作曲", "陈致逸 (HOYO-MiX)"],
            ["编曲", "赵鑫 (HOYO-MiX)"],
            ["乐队", "国际首席爱乐乐团"],
            ["古典吉他", "范晔"],
            ["录音棚", "金田录音棚", "52Hz Studio"],
            ["录音师", "王小四", "黄巍"],
            ["混音师", "黄巍"],
            ["母带制作", "Simon Gibson"],
            ["出品", "HOYO-MiX"],
          ],
        },
        {
          title: "染绿乡园的曲调",
          titleEn: "Melody of Dream Home",
          scene: "幻梦之门",
          start: 0.2,
          links: {
            ne: 1992343572,
            qq: "0025b5Yn297tIc",
          },
          credits: [
            ["作曲", "陈致逸 (HOYO-MiX)"],
            ["编曲", "赵鑫 (HOYO-MiX)"],
            ["乐队", "国际首席爱乐乐团"],
            ["合唱指挥", "齐放"],
            ["合唱", "Sfuture艺术团"],
            ["录音棚", "金田录音棚", "Sound Pro Studio"],
            ["录音师", "王小四", "曹晓冬"],
            ["音频编辑", "徐威"],
            ["混音师", "黄巍"],
            ["母带制作", "Simon Gibson"],
            ["出品", "HOYO-MiX"],
          ],
        },
      ],
    },
    {
      subtitle: "桓那兰那",
      tracks: [
        {
          title: "晨曦初露的曲调",
          titleEn: "Melody of Fresh Dewdrops",
          scene: "一般区域",
          start: 0,
          links: {
            ne: 1992344594,
            qq: "002Bcolj2dlncN",
          },
          credits: [
            ["作曲", "陈致逸 (HOYO-MiX)"],
            ["编曲", "丁谦 (HOYO-MiX)"],
            ["乐队", "Budapest Scoring Orchestra", "国际首席爱乐乐团"],
            ["录音棚", "Budapest Scoring", "金田录音棚"],
            ["录音师", "Viktor Szabó", "王小四"],
            ["混音师", "黄巍"],
            ["母带制作", "Simon Gibson"],
            ["出品", "HOYO-MiX"],
          ],
        },
        {
          title: "幼叶绽生的曲调",
          titleEn: "Melody of Young Leaves",
          scene: "幻梦之门",
          start: 0,
          links: {
            ne: 1992343573,
            qq: "000ySG6L2iDDbp",
          },
          credits: [
            ["作曲", "陈致逸 (HOYO-MiX)"],
            ["编曲", "丁谦 (HOYO-MiX)"],
            ["乐队", "Budapest Scoring Orchestra", "国际首席爱乐乐团"],
            ["合唱指挥", "齐放"],
            ["合唱", "Sfuture艺术团"],
            ["录音棚", "Budapest Scoring", "金田录音棚", "Sound Pro Studio"],
            ["录音师", "Viktor Szabó", "王小四", "曹晓冬"],
            ["音频编辑", "徐威"],
            ["混音师", "Lewis Jones", "黄巍"],
            ["母带制作", "Simon Gibson"],
            ["出品", "HOYO-MiX"],
          ],
        },
      ],
    },
    {
      subtitle: "桓那兰那",
      tracks: [
        {
          title: "生命之谷的曲调",
          titleEn: "Melody of Hidden Seeds",
          scene: "一般区域",
          start: 0,
          links: {
            ne: 1992344595,
            qq: "002C6Szc4cg5sF",
          },
          credits: [
            ["作曲", "陈致逸 (HOYO-MiX)"],
            ["编曲", "姜以君 (HOYO-MiX)"],
            ["乐队", "国际首席爱乐乐团"],
            ["古典吉他", "范晔"],
            ["录音棚", "金田录音棚", "52Hz Studio"],
            ["录音师", "王小四", "黄巍"],
            ["混音师", "黄巍"],
            ["母带制作", "Simon Gibson"],
            ["出品", "HOYO-MiX"],
          ],
        },
        {
          title: "绿野纤绵的曲调",
          titleEn: "Melody of Distant Green Fields",
          scene: "幻梦之门",
          start: 0.2,
          links: {
            ne: 1992343574,
            qq: "001sLMRQ4PUNT2",
          },
          credits: [
            ["作曲", "陈致逸 (HOYO-MiX)"],
            ["编曲", "姜以君 (HOYO-MiX)"],
            ["乐队", "国际首席爱乐乐团"],
            ["古典吉他", "范晔"],
            ["合唱指挥", "齐放"],
            ["合唱", "Sfuture艺术团"],
            ["录音棚", "金田录音棚", "52Hz Studio", "Sound Pro Studio"],
            ["录音师", "王小四", "黄巍", "曹晓冬"],
            ["音频编辑", "徐威"],
            ["混音师", "黄巍"],
            ["母带制作", "Simon Gibson"],
            ["出品", "HOYO-MiX"],
          ],
        },
      ],
    },
    {
      subtitle: "死域",
      tracks: [
        {
          title: "于无生处",
          titleEn: "In Barren Ashes",
          scene: "探索",
          start: 0,
          links: {
            ne: 1992343585,
          },
        },
        {
          title: "余烬的顽抗",
          titleEn: "Struggle of Dying Embers",
          scene: "战斗",
          start: 0,
          links: {
            ne: 1992343586,
          },
        },
      ],
    },
    {
      subtitle: "死域",
      tracks: [
        {
          title: "窒滞之苦",
          titleEn: "Feelings of Smothering",
          scene: "探索",
          start: 0.05,
          links: {
            ne: 1992344603,
            qq: "003Sq2Pu2f9slG",
          },
          credits: [
            ["作曲", "丁谦 (HOYO-MiX)"],
            ["编曲", "丁谦 (HOYO-MiX)"],
            ["混音师", "丁谦 (HOYO-MiX)"],
            ["母带制作", "Simon Gibson"],
            ["出品", "HOYO-MiX"],
          ],
        },
        {
          title: "沉重的恶意",
          titleEn: "Snare Awaiting",
          scene: "战斗",
          start: 0,
          links: {
            ne: 1992344604,
            qq: "003miKC53GfN6B",
          },
          credits: [
            ["作曲", "丁谦 (HOYO-MiX)"],
            ["编曲", "丁谦 (HOYO-MiX)"],
            ["乐队", "国际首席爱乐乐团"],
            ["录音棚", "金田录音棚"],
            ["录音师", "王小四"],
            ["混音师", "黄巍"],
            ["母带制作", "Simon Gibson"],
            ["出品", "HOYO-MiX"],
          ],
        },
      ],
    },
    {
      subtitle: "失梦的国土",
      tracks: [
        {
          title: "失梦之乡",
          titleEn: "Dreamless Earth",
          scene: "探索",
          start: 0.24,
          links: {
            ne: 1992343587,
          },
        },
        {
          title: "失色的灾厄",
          titleEn: "Fatal Confrontation",
          scene: "战斗1",
          start: 0.26,
          links: {
            ne: 1992344605,
          },
        },
        {
          title: "趁生烛尚未殄熄",
          titleEn: "Before the Light Fades",
          scene: "战斗2",
          start: 0,
          links: {
            ne: 1992344606,
          },
        },
      ],
    },
  ],
} as IMAlbum;
