import type { IMAlbum } from "../types";

export default {
  title: "千岩旷望",
  titleEn: "Millelith's Watch",
  image: "https://p2.music.126.net/ragydFCtXKrHRusb28RxLQ==/109951167558151638.jpg",
  musics: [
    {
      subtitle: "无名遗迹",
      tracks: [
        {
          scene: "探索1",
          title: "繁华已逝",
          titleEn: "Decayed in the Darkness",
          start: 0,
          links: {
            ne: 1956543015,
          },
          credits: [
            ["作曲", "丁谦 (HOYO-MiX)"],
            ["编曲", "丁谦 (HOYO-MiX)"],
            ["乐队", "龙之艺交响乐团"],
            ["小提琴", "朱玥"],
            ["录音棚", "上海音像公司录音棚"],
            ["录音师", "莫家伟"],
            ["混音师", "黄巍"],
            ["母带制作", "黄巍"],
            ["出品", "HOYO-MiX"],
          ],
        },
        {
          scene: "探索2",
          title: "破碎的荣耀",
          titleEn: "A Shard From Past Glories",
          start: 0.1,
          links: {
            ne: 1956543016,
          },
          credits: [
            ["作曲", "丁谦 (HOYO-MiX)"],
            ["编曲", "丁谦 (HOYO-MiX)"],
            ["乐队", "龙之艺交响乐团"],
            ["小提琴", "朱玥"],
            ["录音棚", "上海音像公司录音棚"],
            ["录音师", "莫家伟"],
            ["混音师", "黄巍"],
            ["母带制作", "黄巍"],
            ["出品", "HOYO-MiX"],
          ],
        },
        {
          scene: "战斗",
          title: "腾溢的敌意",
          titleEn: "Seething Animosity",
          start: 0,
          links: {
            ne: 1956543022,
          },
          credits: [
            ["作曲", "丁谦 (HOYO-MiX)"],
            ["编曲", "丁谦 (HOYO-MiX)"],
            ["乐队", "龙之艺交响乐团"],
            ["录音棚", "上海音像公司录音棚"],
            ["录音师", "莫家伟"],
            ["混音师", "黄巍"],
            ["母带制作", "黄巍"],
            ["出品", "HOYO-MiX"],
          ],
        },
      ],
    },
    {
      subtitle: "地下水泽",
      tracks: [
        {
          scene: "探索1",
          title: "向时的涟沦",
          titleEn: "Ripples of the Past",
          start: 0,
          links: {
            ne: 1956543017,
          },
          credits: [
            ["作曲", "赵鑫 (HOYO-MiX)"],
            ["编曲", "赵鑫 (HOYO-MiX)"],
            ["混音师", "黄巍"],
            ["母带制作", "黄巍"],
            ["出品", "HOYO-MiX"],
          ],
        },
        {
          scene: "探索2",
          title: "久已消逝之物",
          titleEn: "The Long Lost Days",
          start: 0,
          links: {
            ne: 1956541083,
          },
          credits: [
            ["作曲", "赵鑫 (HOYO-MiX)"],
            ["编曲", "赵鑫 (HOYO-MiX)"],
            ["乐队", "龙之艺交响乐团"],
            ["大提琴", "陈小龙"],
            ["录音棚", "上海音像公司录音棚"],
            ["录音师", "莫家伟"],
            ["混音师", "黄巍"],
            ["母带制作", "黄巍"],
            ["出品", "HOYO-MiX"],
          ],
        },
        {
          scene: "战斗",
          title: "争斗的暗流",
          titleEn: "Undercurrents of Hostility",
          start: 0.05,
          links: {
            ne: 1956543023,
          },
          credits: [
            ["作曲", "赵鑫 (HOYO-MiX)"],
            ["编曲", "赵鑫 (HOYO-MiX)"],
            ["乐队", "龙之艺交响乐团", "国际首席爱乐乐团"],
            ["录音棚", "上海音像公司录音棚", "金田录音棚"],
            ["录音师", "莫家伟", "王小四"],
            ["混音师", "黄巍"],
            ["母带制作", "黄巍"],
            ["出品", "HOYO-MiX"],
          ],
        },
      ],
    },
    {
      subtitle: "荧光狭道",
      tracks: [
        {
          scene: "探索1",
          title: "深邃诡幻之径",
          titleEn: "A Path to Delusions",
          start: 0,
          links: {
            ne: 1956543018,
          },
          credits: [
            ["作曲", "苑迪萌 (HOYO-MiX)"],
            ["编曲", "苑迪萌 (HOYO-MiX)"],
            ["混音师", "黄巍"],
            ["母带制作", "黄巍"],
            ["出品", "HOYO-MiX"],
          ],
        },
        {
          scene: "探索2",
          title: "觭梦沉酣之处",
          titleEn: "A Route to Fantasies",
          start: 0.1,
          links: {
            ne: 1956541084,
          },
          credits: [
            ["作曲", "苑迪萌 (HOYO-MiX)"],
            ["编曲", "苑迪萌 (HOYO-MiX)"],
            ["乐队", "龙之艺交响乐团"],
            ["录音棚", "上海音像公司录音棚"],
            ["录音师", "莫家伟"],
            ["混音师", "黄巍"],
            ["母带制作", "黄巍"],
            ["出品", "HOYO-MiX"],
          ],
        },
        {
          scene: "战斗",
          title: "迫近的险乱",
          titleEn: "Impending Danger",
          start: 0,
          links: {
            ne: 1956543024,
          },
          credits: [
            ["作曲", "苑迪萌 (HOYO-MiX)"],
            ["编曲", "苑迪萌 (HOYO-MiX)"],
            ["乐队", "龙之艺交响乐团", "国际首席爱乐乐团"],
            ["录音棚", "上海音像公司录音棚", "金田录音棚"],
            ["录音师", "莫家伟", "王小四"],
            ["混音师", "黄巍"],
            ["母带制作", "黄巍"],
            ["出品", "HOYO-MiX"],
          ],
        },
      ],
    },
    {
      subtitle: "天钉区域",
      tracks: [
        {
          scene: "探索",
          title: "深埋地心的瑰秘",
          titleEn: "Stories of Remote Antiquity",
          start: 0.23,
          links: {
            ne: 1956543019,
          },
          credits: [
            ["作曲", "陈致逸 (HOYO-MiX)"],
            ["编曲", "陈致逸 (HOYO-MiX)"],
            ["乐队", "龙之艺交响乐团", "国际首席爱乐乐团"],
            ["小提琴", "朱玥"],
            ["大提琴", "陈小龙"],
            ["录音棚", "上海音像公司录音棚", "金田录音棚"],
            ["录音师", "莫家伟", "王小四"],
            ["混音师", "黄巍"],
            ["母带制作", "黄巍"],
            ["出品", "HOYO-MiX"],
          ],
        },
        {
          scene: "战斗",
          title: "激扬的韧战",
          titleEn: "Inevitable Conflict",
          start: 0,
          links: {
            ne: 1956543025,
          },
          credits: [
            ["作曲", "陈致逸 (HOYO-MiX)"],
            ["编曲", "陈致逸 (HOYO-MiX)"],
            ["乐队", "龙之艺交响乐团", "国际首席爱乐乐团"],
            ["小提琴", "柳鸣"],
            ["录音棚", "上海音像公司录音棚", "金田录音棚"],
            ["录音师", "莫家伟", "王小四", "黄巍"],
            ["混音师", "黄巍"],
            ["母带制作", "黄巍"],
            ["出品", "HOYO-MiX"],
          ],
        },
      ],
    },
    // {
    //   tracks: [
    //     {
    //       scene: "原版",
    //       title: "临阵的战栗",
    //       titleEn: "Tremor of Menace",
    //       start: 0,
    //       links: {
    //         ne: 1956543021,
    //       },
    //     },
    //     {
    //       scene: "Remix",
    //       title: "势若风雷",
    //       titleEn: "Irresistible Force",
    //       start: 0,
    //       credits: [
    //         ["作曲", "姜以君 (HOYO-MiX)"],
    //         ["编曲", "姜以君 (HOYO-MiX)"],
    //         ["乐队", "龙之艺交响乐团", "国际首席爱乐乐团"],
    //         ["竹笛", "丁晓逵"],
    //         ["箫", "丁晓逵"],
    //         ["古筝", "申依靖"],
    //         ["琵琶", "孟霄"],
    //         ["二胡", "王颖"],
    //         ["录音棚", "上海音像公司录音棚", "金田录音棚"],
    //         ["录音师", "莫家伟", "王小四", "陈冠男"],
    //         ["混音师", "黄巍"],
    //         ["母带制作", "黄巍"],
    //         ["出品", "HOYO-MiX"],
    //       ],
    //       links: {
    //         ne: 1956543020,
    //         qq: "003Cdisb2ti1Y0",
    //       },
    //     },
    //   ],
    // },
  ],
} as IMAlbum;
